type: com.google.api.codegen.ConfigProto
config_schema_version: 2.0.0
# The settings of generated code in a specific language.
language_settings:
  java:
    package_name: com.google.cloud.tasks.v2beta3
  python:
    package_name: google.cloud.tasks_v2beta3.gapic
  go:
    package_name: cloud.google.com/go/cloudtasks/apiv2beta3
  csharp:
    package_name: Google.Cloud.Tasks.V2Beta3
  ruby:
    package_name: Google::Cloud::Tasks::V2beta3
  php:
    package_name: Google\Cloud\Tasks\V2beta3
  nodejs:
    package_name: tasks.v2beta3
# A list of API interface configurations.
interfaces:
  # The fully qualified name of the API interface.
- name: google.cloud.tasks.v2beta3.CloudTasks
  # Use default retryable codes.
  # Definition for retry/backoff parameters.
  retry_params_def:
  - name: default
    initial_retry_delay_millis: 100
    retry_delay_multiplier: 1.3
    max_retry_delay_millis: 60000
    initial_rpc_timeout_millis: 20000
    rpc_timeout_multiplier: 1
    max_rpc_timeout_millis: 20000
    total_timeout_millis: 600000
  # A list of method configurations.
  # Common properties:
  #
  #   name - The simple name of the method.
  #
  #   flattening - Specifies the configuration for parameter flattening.
  #   Describes the parameter groups for which a generator should produce method
  #   overloads which allow a client to directly pass request message fields as
  #   method parameters. This information may or may not be used, depending on
  #   the target language.
  #   Consists of groups, which each represent a list of parameters to be
  #   flattened. Each parameter listed must be a field of the request message.
  #
  #   required_fields - Fields that are always required for a request to be
  #   valid.
  #
  #   resource_name_treatment - An enum that specifies how to treat the resource
  #   name formats defined in the field_name_patterns and
  #   response_field_name_patterns fields.
  #   UNSET: default value
  #   NONE: the collection configs will not be used by the generated code.
  #   VALIDATE: string fields will be validated by the client against the
  #   specified resource name formats.
  #   STATIC_TYPES: the client will use generated types for resource names.
  #
  #   page_streaming - Specifies the configuration for paging.
  #   Describes information for generating a method which transforms a paging
  #   list RPC into a stream of resources.
  #   Consists of a request and a response.
  #   The request specifies request information of the list method. It defines
  #   which fields match the paging pattern in the request. The request consists
  #   of a page_size_field and a token_field. The page_size_field is the name of
  #   the optional field specifying the maximum number of elements to be
  #   returned in the response. The token_field is the name of the field in the
  #   request containing the page token.
  #   The response specifies response information of the list method. It defines
  #   which fields match the paging pattern in the response. The response
  #   consists of a token_field and a resources_field. The token_field is the
  #   name of the field in the response containing the next page token. The
  #   resources_field is the name of the field in the response containing the
  #   list of resources belonging to the page.
  #
  #   retry_codes_name - Specifies the configuration for retryable codes. The
  #   name must be defined in interfaces.retry_codes_def.
  #
  #   retry_params_name - Specifies the configuration for retry/backoff
  #   parameters. The name must be defined in interfaces.retry_params_def.
  #
  #   field_name_patterns - Maps the field name of the request type to
  #   entity_name of interfaces.collections.
  #   Specifies the string pattern that the field must follow.
  #
  #   timeout_millis - Specifies the default timeout for a non-retrying call. If
  #   the call is retrying, refer to retry_params_name instead.
  methods:
  - name: ListQueues
    retry_codes_name: idempotent
    retry_params_name: default
  - name: GetQueue
    retry_codes_name: idempotent
    retry_params_name: default
  - name: CreateQueue
    retry_params_name: default
  - name: UpdateQueue
    retry_params_name: default
  - name: DeleteQueue
    retry_codes_name: idempotent
    retry_params_name: default
    timeout_millis: 10000
  - name: PurgeQueue
    retry_params_name: default
  - name: PauseQueue
    retry_params_name: default
  - name: ResumeQueue
    retry_params_name: default
  - name: GetIamPolicy
    retry_codes_name: idempotent
    retry_params_name: default
    timeout_millis: 10000
  - name: SetIamPolicy
    retry_params_name: default
    timeout_millis: 10000
  - name: TestIamPermissions
    retry_codes_name: idempotent
    retry_params_name: default
    timeout_millis: 10000
  - name: ListTasks
    retry_params_name: default
    retry_codes_name: idempotent
    timeout_millis: 10000
  - name: GetTask
    retry_params_name: default
    retry_codes_name: idempotent
  - name: CreateTask
    retry_params_name: default
  - name: DeleteTask
    retry_params_name: default
    retry_codes_name: idempotent
  - name: RunTask
    retry_params_name: default
